In [3]:
import pandas as pd 
fixed_entries= [
    {
        "question": "what is the annual fee",
        "answer": "The annual fee is Rs. 500.",
        "keywords": "fee cost price charge",
        "category": "billing"
    },
    {
        "question": "how to reset password",
        "answer": "Go to Settings > Reset Password.",
        "keywords": "password reset login",
        "category": "account"
    },
    {
        "question": "what are your working hours",
        "answer": "We are open 9 AM to 5 PM.",
        "keywords": "hours timing open time",
        "category": "general"
    },
    {
        "question": "how can i pay the fee",
        "answer": "You can pay via UPI, card, or net banking.",
        "keywords": "pay payment upi fee",
        "category": "billing"
    }
]
    # Roll number: 1024170084
# Last two digits: 8, 4
# 8 % 3 = 2 -> general
# 4 % 3 = 1 -> account

custom_entries= [
    {
        "question": "where is the college library",
        "answer": "The college library is located near the academic block.",
        "keywords": "library location campus",
        "category": "general"
    },
    {
        "question": "how do i update my registered mobile number",
        "answer": "You can update your mobile number from account settings.",
        "keywords": "mobile update account",
        "category": "account"
    }
]

data= fixed_entries + custom_entries

df= pd.DataFrame(data)
df

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs. 500.,fee cost price charge,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing
4,where is the college library,The college library is located near the academ...,library location campus,general
5,how do i update my registered mobile number,You can update your mobile number from account...,mobile update account,account

In [5]:
def score_query(query,df): 
    query= query.lower()
    result= []

    for i, row in df.iterrows():
        score= sum(word in row["keywords"].split() for word in query.split())
        if score>0:
            result.append([row["question"], row["answer"],score])

    return pd.DataFrame(
    result,
    columns=["question", "answer", "score"]).sort_values("score", ascending= False)

score_query("fee payment",df)

                 question                                      answer  score
1   how can i pay the fee  You can pay via UPI, card, or net banking.      2
0  what is the annual fee                  The annual fee is Rs. 500.      1

In [6]:
def same_category(category_name, df):
    return df[df["category"] == category_name]
same_category("general",df)

,question,answer,keywords,category
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
4,where is the college library,The college library is located near the academ...,library location campus,general

In [7]:
index=0 
new_keyword= input("Enter new keyword: ")
df.loc[index, "keywords"] += " " + new_keyword
df.to_csv("1024170084_faq_data.csv", index= False)
df

KeyboardInterrupt: Interrupted by user

In [8]:
df.groupby("category").size()

category
account    2
billing    2
general    2
dtype: int64

In [ ]:
def score_query_tie(query,df):
    query= query.lower()
    result=[]

    for i,row in df.iterrows():
        score= sum(word in row["keywords"].split() for word in query.split())

        result.append([row["questions"], score])
    result= pd.DataFrame(result,columns=["question", "score"])
    max_score= result["score"].max()
    return re